%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-rc-genicam-api
Version:        2.3.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rc_genicam_api package

License:        BSD
URL:            http://wiki.ros.org/rc_genicam_api
Source0:        %{name}-%{version}.tar.gz

Requires:       libpng-devel
Requires:       libusbx
Requires:       ros-noetic-catkin
BuildRequires:  cmake
BuildRequires:  libpng-devel
BuildRequires:  libusbx
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
GenICam/GigE Vision Convenience Layer. This package combines the Roboception
convenience layer for images with the GenICam reference implementation and a
GigE Vision transport layer. It is a self contained package that permits
configuration and image streaming of GenICam / GigE Vision 2.0 compatible
cameras like the Roboception rc_visard. This package also provides some tools
that can be called from the command line for discovering cameras, changing their
configuration and streaming images. Although the tools are meant to be useful
when working in a shell or in a script, their main purpose is to serve as
example on how to use the API for reading and setting parameters, streaming and
synchronizing images. See LICENSE.md for licensing terms of the different parts.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Apr 02 2020 Felix Ruess <felix.ruess@roboception.de> - 2.3.4-1
- Autogenerated by Bloom

