%{?!ros_distro:%global ros_distro rolling}
%global pkg_name rc_genicam_api
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-rc-genicam-api
Version:        2.8.6
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            http://wiki.ros.org/rc_genicam_api
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
GenICam/GigE Vision Convenience Layer. This package combines the Roboception
convenience layer for images with the GenICam reference implementation and a
GigE Vision transport layer. It is a self contained package that permits
configuration and image streaming of GenICam / GigE Vision 2.0 compatible
cameras like the Roboception rc_visard. This package also provides some tools
that can be called from the command line for discovering cameras, changing their
configuration and streaming images. Although the tools are meant to be useful
when working in a shell or in a script, their main purpose is to serve as
example on how to use the API for reading and setting parameters, streaming and
synchronizing images. See LICENSE.md for licensing terms of the different parts.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
GenICam/GigE Vision Convenience Layer. This package combines the Roboception
convenience layer for images with the GenICam reference implementation and a
GigE Vision transport layer. It is a self contained package that permits
configuration and image streaming of GenICam / GigE Vision 2.0 compatible
cameras like the Roboception rc_visard. This package also provides some tools
that can be called from the command line for discovering cameras, changing their
configuration and streaming images. Although the tools are meant to be useful
when working in a shell or in a script, their main purpose is to serve as
example on how to use the API for reading and setting parameters, streaming and
synchronizing images. See LICENSE.md for licensing terms of the different parts.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
GenICam/GigE Vision Convenience Layer. This package combines the Roboception
convenience layer for images with the GenICam reference implementation and a
GigE Vision transport layer. It is a self contained package that permits
configuration and image streaming of GenICam / GigE Vision 2.0 compatible
cameras like the Roboception rc_visard. This package also provides some tools
that can be called from the command line for discovering cameras, changing their
configuration and streaming images. Although the tools are meant to be useful
when working in a shell or in a script, their main purpose is to serve as
example on how to use the API for reading and setting parameters, streaming and
synchronizing images. See LICENSE.md for licensing terms of the different parts.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Wed Jun 03 2026 Felix Ruess <felix.ruess@roboception.de> - 2.8.6-1
- Autogenerated by Bloom

* Tue Jun 02 2026 Felix Ruess <felix.ruess@roboception.de> - 2.8.5-1
- Autogenerated by Bloom

* Tue Apr 28 2026 Felix Ruess <felix.ruess@roboception.de> - 2.8.1-2
- Autogenerated by Bloom

* Tue Apr 21 2026 Felix Ruess <felix.ruess@roboception.de> - 2.8.1-1
- Autogenerated by Bloom
